[package]
name = "j"
version = "0.1.1"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
license = "WTFPL/MIT/Apache"
description = "a command runner"
homepage = "https://github.com/casey/j"

[dependencies]

brev = "0.1.6"
