[package]
name = "j"
version = "0.2.6"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
license = "WTFPL/MIT/Apache-2.0"
description = "a command runner"
homepage = "https://github.com/casey/j"

[dependencies]

regex = "^0.1.77"
clap = "^2.0.0"
tempdir = "^0.3.5"
lazy_static = "^0.2.1"
brev = "^0.1.6"
